### ISSUE TITLE
user.css in data directory has no effect

### ISSUE THREAD

**Issue by aegidius77** [simon-mettler/shaarli-theme#1]
Hi,

Copying this ```user.css``` file in shaarli v0.12.1 ```/data``` directory has no effect :

[https://github.com/simon-mettler/shaarli-theme](https://github.com/simon-mettler/shaarli-theme)

Did I miss something ?

**Comment by simon-mettler** [comment]
Closing, because already discussed here: https://github.com/shaarli/Shaarli/issues/1986
Probably a server config issue, no issue with user.css file.
